spring:
  profiles:
    active: dev  # Cambia a 'prod' en produccion
  jpa:
    properties:
      hibernate:
        format_sql: true
  cache:
    type: caffeine  # Usa cache en memoria
consultancy:
  fixed:
    price: ${CONSULTANCY_PRICE}



