spring:
  datasource:
    url: jdbc:postgresql://${DEV_DB_HOST}:${DEV_DB_PORT}/${DEV_DB_NAME}
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true  # Muestra consultas SQL en logs
  mail:
    host: ${MAIL_HOST_DEV}
    port: ${MAIL_PORT_DEV}
    username: ${MAIL_USERNAME_DEV}
    password: ${MAIL_PASSWORD_DEV}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  sql:
    init:
      mode: always  # Ejecuta scripts en `resources/schema.sql` y `data.sql`
server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always
    include-exception: true
mercadopago:
    access-token: ${MERCADO_PAGO_ACCESS_TOKEN_TEST}
    secret-key: ${MERCADO_PAGO_SECRET_KEY_TEST}
    public-key: ${MP_PUBLIC_KEY_TEST}
    notification-url: https://1dd2-181-41-229-154.ngrok-free.app/alquila-seg/payments/webhooks
consultancy:
  fixed:
    price: ${CONSULTANCY_PRICE}
app:
  jwt:
    secret: ${APP_JWT_SECRET}
    expiration: 86400000
logging:
  level:
    com:
     example:
       alquila_seguro_backend:
         controller:
           PaymentController: DEBUG
         mercadopago:
           utils:
             SignatureHelper: DEBUG

    root: INFO
