spring:
  datasource:
    url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 20000
  jpa:
    hibernate:
      ddl-auto: validate  # Verifica que las tablas existen, pero NO las modifica
    show-sql: false  # Desactiva logs SQL en producción
  mail:
    host: ${MAIL_HOST_PROD}
    port: ${MAIL_PORT_PROD}
    username: ${MAIL_USERNAME_PROD}
    password: ${MAIL_PASSWORD_PROD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  sql:
    init:
      mode: never  # No carga scripts automáticamente en producción
server:
  port: 8080
  error:
    include-message: never
    include-binding-errors: never
    include-stacktrace: never
    include-exception: false
logging:
  level:
    root: WARN
    org.springframework.web: ERROR
    org.hibernate.SQL: OFF
mercadopago:
    access-token: ${MERCADO_PAGO_ACCESS_TOKEN}
    secret-key: ${MERCADO_PAGO_SECRET_KEY}
    notification-url: https://www.alquilaseguro.com.ar/alquila-seg/payments/webhooks
consultancy:
  fixed:
    price: ${CONSULTANCY_PRICE}
app:
  jwt:
    secret: ${APP_JWT_SECRET}
    expiration: 86400000