spring:
  profiles:
    active: dev  # Cambia a 'prod' en produccion
  jpa:
    properties:
      hibernate:
        format_sql: true
  cache:
    type: caffeine  # Usa cache en memoria
  mail:
    host: ${MAIL_HOST_${spring.profiles.active:dev}}
    port: ${MAIL_PORT_${spring.profiles.active:dev}}}
    username: ${MAIL_USERNAME_${spring.profiles.active:dev}}
    password: ${MAIL_PASSWORD_${spring.profiles.active:dev}}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  file:
    name: logs/alquila-seguro-backend.log
  level:
    root: INFO
    org.springframework.web: WARN
    org.hibernate.SQL: ERROR
mercadopago:
  access-token: ${MERCADO_PAGO_ACCESS_TOKEN_TEST}
  secret-key: ${SECRET_KEY}
consultancy:
  fixed:
    price: ${CONSULTANCY_PRICE}



